package com.barteklipinski.testcasefactory.integration

import com.barteklipinski.testcasefactory.*
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4
import strikt.api.expectThat
import strikt.assertions.hasSize

@RunWith(JUnit4::class)
class IntegrationTestN {

    @Test
    fun `library works correctly for ten types of inputs`() {
        // given
        val inputs1 = arrayOf(1, 2)
        val input2 = "a"
        val inputs3 = listOf(1.2f, 2.3f, 3.4f)
        val inputs4 = Fruit.values()
        val input6 = "example"
        val input7 = "example2"
        val inputs8 = listOf('a', 'b', 'c')
        val input9 = "abc"
        val inputs10 = arrayListOf(4.5f, 5.6f)
        val expected = 124.5f

        // when
        val testCases = combinationsOf {
            anyOf(inputs1) and
                    exactlyOrNull(input2) and
                    anyOf(inputs3[0], inputs3[1], inputs3[2]) and
                    anyOf(inputs4) excluding (Fruit.Passionfruit) and
                    anyBoolean() and
                    anyOf(input6) and
                    exactly(input7) and
                    anyOf(inputs8) excluding ('b') excluding ('c') and
                    exactly(input9) and
                    anyOf(inputs10[0], inputs10[1])
        } expect (expected)

        // then
        val testCasesList = testCases.toList()
        expectThat(testCasesList).hasSize(48)
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            expects = expected,
        )
    }


    @Test
    fun `library works correctly for eleven types of inputs`() {
        // given
        val inputs1 = arrayOf(1, 2)
        val input2 = "a"
        val inputs3 = listOf(1.2f, 2.3f, 3.4f)
        val inputs4 = Fruit.values()
        val input6 = "example"
        val input7 = "example2"
        val inputs8 = listOf('a', 'b', 'c')
        val input9 = "abc"
        val inputs10 = arrayListOf(4.5f, 5.6f)
        val inputs11 = listOf(4, 5, 6)
        val expected = 124.5f

        // when
        val testCases = combinationsOf {
            anyOf(inputs1) and
                    exactlyOrNull(input2) and
                    anyOf(inputs3[0], inputs3[1], inputs3[2]) and
                    anyOf(inputs4) excluding (Fruit.Passionfruit) and
                    anyBoolean() and
                    anyOf(input6) and
                    exactly(input7) and
                    anyOf(inputs8) excluding ('b') excluding ('c') and
                    exactly(input9) and
                    anyOf(inputs10[0], inputs10[1]) and
                    anyOf(inputs11) excluding(6)
        } expect (expected)

        // then
        val testCasesList = testCases.toList()
        expectThat(testCasesList).hasSize(96)
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[0],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[0],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = true,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[0],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[1],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[0],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = input2,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
        expectThat(testCasesList).containsTestCase(
            inputFirst = inputs1[1],
            inputSecond = null,
            inputThird = inputs3[2],
            inputFourth = Fruit.Mango,
            inputFifth = false,
            inputSixth = input6,
            inputSeventh = input7,
            inputEighth = inputs8[0],
            inputNinth = input9,
            inputTenth = inputs10[1],
            inputEleventh = inputs11[1],
            expects = expected,
        )
    }
}